packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint-config-airbnb-base: '*'

yarnPath: .yarn/releases/yarn-3.0.1.cjs
