version: 2
jobs:
  build:
    working_directory: ~/lineup
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps3-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: deps3-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run:
          name: dist
          command: npm run dist
      - store_artifacts:
          path: dist
      - run: #update build doc and readme
          name: update api
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ] || [ "${CIRCLE_BRANCH}" == "master" ] ; then
                git clone git@github.com:lineupjs/lineupengine.js.org.git
                cd lineupengine.js.org
                rm -rf "${CIRCLE_BRANCH}/"
                rm README.md
                cp ../README.md README.md
                mv ../build "${CIRCLE_BRANCH}"
                git config user.email "sam@sgratzl.com"
                git config user.name "Samuel Gratzl"
                git add -A
                git commit -m "auto updating ${CIRCLE_BRANCH}" -m "trigger: ${CIRCLE_BUILD_URL}"
                git push origin master
            fi

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
